"""Generate a deterministic SQL seed from the raw Skills-Ring CSV export."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "raw-database" / "HacKU" / "database_demo2_csv"
TARGET = ROOT / "supabase" / "seed.sql"

TABLES = [
    "categories",
    "users",
    "skills",
    "skill_values",
    "time_slots",
    "offers",
    "needs",
    "offer_availability",
    "need_availability",
    "exchange_preferences",
    "system_config",
    "reliability_history",
    "matches",
    "recommendation_rankings",
    "recommendation_events",
    "exchanges",
    "exchange_matches",
    "exchange_participants",
    "commitments",
    "sessions",
    "contributions",
    "evaluations",
    "disputes",
    "withdrawals",
]

NUMERIC = {
    "base_value",
    "value_adjustment",
    "value_per_session_snapshot",
    "base_value_snapshot",
    "adjustment_snapshot",
    "contribution_value",
    "reliability_score",
    "completion_rate",
    "on_time_rate",
    "commitment_fulfillment_rate",
    "response_rate",
    "dispute_free_rate",
    "cancellation_rate",
    "no_show_rate",
    "compatibility_score",
    "level_score",
    "availability_score",
    "convenience_score",
    "reciprocity_score",
    "contribution_score",
    "risk_score",
    "level_value_score",
    "value_balance_score",
    "final_score",
}
INTEGER = {
    "slot_id",
    "sort_order",
    "duration_minutes",
    "max_sessions",
    "sessions_needed",
    "rank_position",
    "scheduled_duration_minutes",
    "actual_duration_minutes",
}
BOOLEAN = {"on_time", "completed_as_agreed", "engaged", "would_exchange_again", "rematch_required"}
NULLABLE = {"avatar_url", "description", "effective_to", "semester", "user_c", "offer_id_c", "need_id_c", "scheduled_time", "actual_duration_minutes", "notes", "completed_at", "base_value_snapshot", "adjustment_snapshot", "contribution_value", "comment", "resolution", "session_id", "rank_position", "value_per_session_snapshot"}


def sql_value(column: str, value: str) -> str:
    if value == "" and column in NULLABLE:
        return "NULL"
    if column in BOOLEAN:
        return "TRUE" if value in {"1", "true", "TRUE"} else "FALSE"
    if column in NUMERIC or column in INTEGER:
        return value or "NULL"
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def table_insert(table: str) -> list[str]:
    path = SOURCE / f"{table}.csv"
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if not rows:
        return [f"-- {table}: 0 rows in the raw snapshot"]
    columns = list(rows[0])
    lines = [
        f"-- {table}: {len(rows)} rows",
        f"insert into public.{table} ({', '.join(columns)}) values",
    ]
    values = []
    for row in rows:
        values.append("  (" + ", ".join(sql_value(column, row[column]) for column in columns) + ")")
    lines.append(",\n".join(values) + ";")
    return lines


def main() -> None:
    sections = [
        "-- Generated by scripts/generate-supabase-seed.py; do not edit by hand.",
        "-- Source: raw-database/HacKU/database_demo2_csv.",
        "-- Apply supabase/migrations/20261003000000_skills_ring_raw_schema.sql first.",
        "",
        "begin;",
        "",
    ]
    for table in TABLES:
        sections.extend(table_insert(table))
        sections.append("")
    sections.extend([
        "commit;",
        "",
        "-- Expected live view row count after seeding: 300.",
        "-- current_user_reliability is derived from reliability_history and is not copied as a table.",
        "",
    ])
    TARGET.write_text("\n".join(sections), encoding="utf-8")


if __name__ == "__main__":
    main()
