import { useState } from "react";
import { type Action, type Exchange, type Person, type State, name, people } from "./domain";
import { CalendarExport } from "./CalendarExport";

export function Coordination({ e, state, user, act }: { e: Exchange; state: State; user: Person; act: (action: Action) => void }) {
  const [text, setText] = useState("");
  const [leg, setLeg] = useState(e.legs.find((l) => l.provider === user || l.receiver === user)?.id || e.legs[0].id);
  const [place, setPlace] = useState("");
  const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  const messages = (state.messages || []).filter((m) => m.exchange === e.id);
  const bookings = (state.bookings || []).filter((b) => b.exchange === e.id);
  const selectedLeg = e.legs.find((l) => l.id === leg)!;
  const confirmed = ["confirmed", "active", "partially settled"].includes(e.status);
  return <div className="coordination">
    <section className="recovery-section"><h3>Conversation</h3><p>Messages stay with this {e.legs.length === 2 ? "exchange" : "ring"}. Before everyone confirms, please keep contact details private.</p>
      <div className="message-thread" role="log" aria-label="Exchange messages">{messages.length ? messages.map((m) => <div className="message-item" key={m.id}><strong>{people[m.author].name}</strong><time dateTime={m.createdAt}>{new Date(m.createdAt).toLocaleString()}</time><p>{m.text}</p></div>) : <p className="muted">No messages yet. Start with a question about the proposed terms.</p>}</div>
      <form onSubmit={(event) => { event.preventDefault(); if (!text.trim()) return; act({ type: "message", exchange: e.id, user, text }); setText(""); }}><label>Your message<textarea value={text} onChange={(event) => setText(event.target.value)} maxLength={1000} rows={3} required /></label><button className="button primary" type="submit">Send message</button></form>
    </section>
    <section className="recovery-section"><h3>Session times</h3><p>Times are shown in your timezone ({timezone}). Both people on a service leg must accept. To reschedule, cancel the old time and propose a new one.</p>
      {bookings.map((booking) => { const service = e.legs.find((l) => l.id === booking.leg)!; const involved = [service.provider, service.receiver].includes(user); return <div className="booking-card" key={booking.id}><strong>{name(service.provider)} → {name(service.receiver)} · {service.skill}</strong><p><time dateTime={booking.start}>{new Date(booking.start).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })}</time> · {service.duration} min · {booking.place || "Place to be agreed"}</p><p>Status: {booking.status}. {booking.status === "proposed" && `${booking.acceptedBy.map(name).join(", ")} accepted.`}</p>{involved && <div className="button-row">{booking.status === "proposed" && !booking.acceptedBy.includes(user) && <button className="button" onClick={() => act({ type: "acceptBooking", exchange: e.id, booking: booking.id, user })}>Accept time</button>}{["proposed", "accepted"].includes(booking.status) && <button className="button" onClick={() => act({ type: "cancelBooking", exchange: e.id, booking: booking.id, user })}>Cancel time</button>}{booking.status === "accepted" && <><CalendarExport id={booking.id} start={booking.start} minutes={service.duration} title={`${service.skill} with ${name(service.provider)} and ${name(service.receiver)}`} place={booking.place} /><button className="button" disabled={Date.parse(booking.start) > Date.now()} onClick={() => act({ type: "complete", exchange: e.id, leg: service.id, booking: booking.id })}>Record completed session</button><button className="button" disabled={Date.now() < Date.parse(booking.start) + 15 * 60000} onClick={() => act({ type: "noShow", exchange: e.id, booking: booking.id, user })}>Report no-show</button></>}</div>}</div>; })}
      {confirmed && <form className="booking-form" onSubmit={(event) => { event.preventDefault(); const value = new FormData(event.currentTarget).get("start") as string; if (!value) return; act({ type: "booking", exchange: e.id, leg, user, start: new Date(value).toISOString(), timezone, place }); event.currentTarget.reset(); }}><label>Service<select value={leg} onChange={(event) => setLeg(event.target.value)}>{e.legs.filter((l) => l.provider === user || l.receiver === user).map((l) => <option key={l.id} value={l.id}>{name(l.provider)} gives {l.skill} to {name(l.receiver)}</option>)}</select></label><label>Exact time<input name="start" type="datetime-local" required /></label><label>{selectedLeg.mode === "Online" ? "Meeting link or platform" : "Public meeting place"}<input value={place} onChange={(event) => setPlace(event.target.value)} maxLength={180} placeholder={selectedLeg.mode === "Online" ? "Video link or platform" : "Library or community venue"} required /></label><button className="button primary" type="submit">Propose session time</button></form>}
      {!confirmed && <p className="muted">Session times open once everyone has confirmed the exchange.</p>}
      <p className="muted">No-show reports become available 15 minutes after an accepted start time. Local demo reminders appear in your update history; calendar export works on this device.</p>
    </section>
  </div>;
}
